### ISSUE TITLE
soup.io can't be embedded with iframe

### ISSUE THREAD

**Issue by meksor** [soup/opensoup#1]
When I try to embed a soup with iframe, it just doesn't show anything...

**Comment by norpol** [comment]
This is on purpose, see [mdn X-Frame-Options](https://developer.mozilla.org/en-US/docs/Web/HTTP/X-Frame-Options).
+ this repository was intended as a rewrite of soup.io, so this repo doesn't include the productive version.

**Comment by norpol** [comment]
👍
